# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: ivan-na

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: JP Ivan Dong

description: Stylish Jekyll Theme
author:
  name: Ivan
  email: ivandjp@163.com
  github: Ivan-na
  #twitter: dbtek
  #pinterest: asd123
  linkedin: cn.linkedin.com/in/ivandjp
  bio: This is my page
  email_md5: 8c127ee8fec4748aec269f4cf97dafd7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate